apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: octomaton-github
  namespace: octomaton
  labels:
    app.kubernetes.io/name: octomaton
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: octomaton-github
    creationPolicy: Owner
  data:
    - secretKey: app-id
      remoteRef:
        key: octomaton-github-app-id
    - secretKey: private-key
      remoteRef:
        key: octomaton-github-private-key
    - secretKey: webhook-secret
      remoteRef:
        key: octomaton-github-webhook-secret
